#!/usr/bin/env ruby

require "bundler/setup"
require 'active_support/all'
require 'csv'
require 'dotenv'
require 'pipedrive-ruby'
require 'pry'

NURTURE_STAGE_ID = 92
HOUSE_LIST_ID = 47848

Dotenv.load

puts "Getting house list..."

emails = []
i = 0
while (i += 1)
  puts "Getting page #{i}"
  resp = HTTParty.get(
    "https://api.sendgrid.com/v3/contactdb/lists/#{HOUSE_LIST_ID}/recipients",
    query: { page_size: 1000, page: i },
    headers: { 'Authorization' => "Bearer #{ENV['SENDGRID_API_TOKEN']}" }
  )

  page_emails = Array(resp['recipients']).map { |r| r['email'] }
  emails.push(*page_emails)
  break if page_emails.length == 0
end

emails = emails.map(&:downcase).uniq

puts "Found #{emails.length} emails on house list."

Pipedrive.authenticate(ENV['PIPEDRIVE_TOKEN'])

deals = Pipedrive::Base.all(Pipedrive::Base.get("/stages/#{NURTURE_STAGE_ID}/deals", query: {everyone: '1'}))

deal_ids = deals.map(&:id)
emails = []

puts "Found #{deal_ids.length} deals in nurture."

deal_ids.each do |deal_id|
  participants = Pipedrive::Base.get("/deals/#{deal_id}/participants")['data']

  participants.each do |p|
    emails << p.dig('person', 'email', 0, 'value')
  end
end

puts "Before cleaning, found #{emails.length} emails to nurture."

emails = emails.
          map(&:downcase).
          uniq.
          reject { |e| e.ends_with?("@dobt.co") }

puts "After cleaning, found #{emails.length} emails to nurture."
